server:
  port: 8081

spring:
  config:
      activate:
        on-profile: test

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  api-docs:
    enabled: true
    path: /api-docs